// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RubbleTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Shared.Serialization;
    using Eco.Gameplay.Objects;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Core.Items;

    [BecomesRubble(typeof(ShaleRubbleSet1Chunk1Object), typeof(ShaleRubbleSet1Chunk2Object), typeof(ShaleRubbleSet1Chunk3Object))]
    [BecomesRubble(typeof(ShaleRubbleSet2Chunk1Object), typeof(ShaleRubbleSet2Chunk2Object), typeof(ShaleRubbleSet2Chunk3Object), typeof(ShaleRubbleSet2Chunk4Object))]
    [BecomesRubble(typeof(ShaleRubbleSet3Chunk1Object), typeof(ShaleRubbleSet3Chunk2Object), typeof(ShaleRubbleSet3Chunk3Object))]
    [BecomesRubble(typeof(ShaleRubbleSet4Chunk1Object), typeof(ShaleRubbleSet4Chunk2Object), typeof(ShaleRubbleSet4Chunk3Object))]
    [Tag("Minable")]
    public partial class ShaleBlock : Block { }

    [Serialized, Tag("FastPickupable")] public partial class ShaleRubbleSet1Chunk1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable")] public partial class ShaleRubbleSet1Chunk2Object : RubbleObject<ShaleItem> { }

    [BecomesRubble(typeof(ShaleRubbleSet1Chunk3Split1Object), typeof(ShaleRubbleSet1Chunk3Split2Object)), Tag("MinableRubble")]
    [Serialized] public partial class ShaleRubbleSet1Chunk3Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet1Chunk3Split1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet1Chunk3Split2Object : RubbleObject<ShaleItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet2Chunk1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet2Chunk2Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet2Chunk3Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet2Chunk4Object : RubbleObject<ShaleItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet3Chunk1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet3Chunk2Object : RubbleObject<ShaleItem> { }
    [BecomesRubble(typeof(ShaleRubbleSet3Chunk3Split1Object), typeof(ShaleRubbleSet3Chunk3Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class ShaleRubbleSet3Chunk3Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet3Chunk3Split1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet3Chunk3Split2Object : RubbleObject<ShaleItem> { }

    [BecomesRubble(typeof(ShaleRubbleSet4Chunk1Split1Object), typeof(ShaleRubbleSet4Chunk1Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class ShaleRubbleSet4Chunk1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet4Chunk1Split1Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet4Chunk1Split2Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet4Chunk2Object : RubbleObject<ShaleItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class ShaleRubbleSet4Chunk3Object : RubbleObject<ShaleItem> { }
}
