// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RubbleTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Shared.Serialization;
    using Eco.Gameplay.Objects;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Core.Items;

    [BecomesRubble(typeof(SlagRubbleSet1Chunk1Object), typeof(SlagRubbleSet1Chunk2Object), typeof(SlagRubbleSet1Chunk3Object))]
    [BecomesRubble(typeof(SlagRubbleSet2Chunk1Object), typeof(SlagRubbleSet2Chunk2Object), typeof(SlagRubbleSet2Chunk3Object), typeof(SlagRubbleSet2Chunk4Object))]
    [BecomesRubble(typeof(SlagRubbleSet3Chunk1Object), typeof(SlagRubbleSet3Chunk2Object), typeof(SlagRubbleSet3Chunk3Object))]
    [BecomesRubble(typeof(SlagRubbleSet4Chunk1Object), typeof(SlagRubbleSet4Chunk2Object), typeof(SlagRubbleSet4Chunk3Object))]
    [Tag("Minable")]
    public partial class SlagBlock : Block { }

    [Serialized, Tag("FastPickupable")] public partial class SlagRubbleSet1Chunk1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable")] public partial class SlagRubbleSet1Chunk2Object : RubbleObject<SlagItem> { }

    [BecomesRubble(typeof(SlagRubbleSet1Chunk3Split1Object), typeof(SlagRubbleSet1Chunk3Split2Object)), Tag("MinableRubble")]
    [Serialized] public partial class SlagRubbleSet1Chunk3Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet1Chunk3Split1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet1Chunk3Split2Object : RubbleObject<SlagItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet2Chunk1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet2Chunk2Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet2Chunk3Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet2Chunk4Object : RubbleObject<SlagItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet3Chunk1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet3Chunk2Object : RubbleObject<SlagItem> { }
    [BecomesRubble(typeof(SlagRubbleSet3Chunk3Split1Object), typeof(SlagRubbleSet3Chunk3Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class SlagRubbleSet3Chunk3Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet3Chunk3Split1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet3Chunk3Split2Object : RubbleObject<SlagItem> { }

    [BecomesRubble(typeof(SlagRubbleSet4Chunk1Split1Object), typeof(SlagRubbleSet4Chunk1Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class SlagRubbleSet4Chunk1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet4Chunk1Split1Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet4Chunk1Split2Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet4Chunk2Object : RubbleObject<SlagItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SlagRubbleSet4Chunk3Object : RubbleObject<SlagItem> { }
}
