// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RubbleTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Shared.Serialization;
    using Eco.Gameplay.Objects;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Core.Items;

    [BecomesRubble(typeof(SulfurRubbleSet1Chunk1Object), typeof(SulfurRubbleSet1Chunk2Object), typeof(SulfurRubbleSet1Chunk3Object))]
    [BecomesRubble(typeof(SulfurRubbleSet2Chunk1Object), typeof(SulfurRubbleSet2Chunk2Object), typeof(SulfurRubbleSet2Chunk3Object), typeof(SulfurRubbleSet2Chunk4Object))]
    [BecomesRubble(typeof(SulfurRubbleSet3Chunk1Object), typeof(SulfurRubbleSet3Chunk2Object), typeof(SulfurRubbleSet3Chunk3Object))]
    [BecomesRubble(typeof(SulfurRubbleSet4Chunk1Object), typeof(SulfurRubbleSet4Chunk2Object), typeof(SulfurRubbleSet4Chunk3Object))]
    [Tag("Minable")]
    public partial class SulfurBlock : Block { }

    [Serialized, Tag("FastPickupable")] public partial class SulfurRubbleSet1Chunk1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable")] public partial class SulfurRubbleSet1Chunk2Object : RubbleObject<SulfurItem> { }

    [BecomesRubble(typeof(SulfurRubbleSet1Chunk3Split1Object), typeof(SulfurRubbleSet1Chunk3Split2Object)), Tag("MinableRubble")]
    [Serialized] public partial class SulfurRubbleSet1Chunk3Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet1Chunk3Split1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet1Chunk3Split2Object : RubbleObject<SulfurItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet2Chunk1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet2Chunk2Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet2Chunk3Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet2Chunk4Object : RubbleObject<SulfurItem> { }

    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet3Chunk1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet3Chunk2Object : RubbleObject<SulfurItem> { }
    [BecomesRubble(typeof(SulfurRubbleSet3Chunk3Split1Object), typeof(SulfurRubbleSet3Chunk3Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class SulfurRubbleSet3Chunk3Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet3Chunk3Split1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet3Chunk3Split2Object : RubbleObject<SulfurItem> { }

    [BecomesRubble(typeof(SulfurRubbleSet4Chunk1Split1Object), typeof(SulfurRubbleSet4Chunk1Split2Object))]
    [Serialized, Tag("MinableRubble")]    public partial class SulfurRubbleSet4Chunk1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet4Chunk1Split1Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet4Chunk1Split2Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet4Chunk2Object : RubbleObject<SulfurItem> { }
    [Serialized, Tag("FastPickupable"), Tag("Pickupable")] public partial class SulfurRubbleSet4Chunk3Object : RubbleObject<SulfurItem> { }
}
